// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.puglieseweb.server.domain;

import com.puglieseweb.server.domain.Feedback;
import java.util.List;
import java.util.Random;
import org.springframework.stereotype.Component;

privileged aspect FeedbackDataOnDemand_Roo_DataOnDemand {
    
    declare @type: FeedbackDataOnDemand: @Component;
    
    private Random FeedbackDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Feedback> FeedbackDataOnDemand.data;
    
    public Feedback FeedbackDataOnDemand.getNewTransientFeedback(int index) {
        com.puglieseweb.server.domain.Feedback obj = new com.puglieseweb.server.domain.Feedback();
        obj.setFeedback("feedback_" + index);
        java.lang.String name = "name_" + index;
        if (name.length() > 30) {
            name  = name.substring(0, 30);
        }
        obj.setName(name);
        obj.setEmail("email_" + index);
        return obj;
    }
    
    public Feedback FeedbackDataOnDemand.getSpecificFeedback(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Feedback obj = data.get(index);
        return Feedback.findFeedback(obj.getId());
    }
    
    public Feedback FeedbackDataOnDemand.getRandomFeedback() {
        init();
        Feedback obj = data.get(rnd.nextInt(data.size()));
        return Feedback.findFeedback(obj.getId());
    }
    
    public boolean FeedbackDataOnDemand.modifyFeedback(Feedback obj) {
        return false;
    }
    
    public void FeedbackDataOnDemand.init() {
        data = com.puglieseweb.server.domain.Feedback.findFeedbackEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Feedback' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<com.puglieseweb.server.domain.Feedback>();
        for (int i = 0; i < 10; i++) {
            com.puglieseweb.server.domain.Feedback obj = getNewTransientFeedback(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
