// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package com.puglieseweb.client.managed.ui;

import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.safehtml.shared.SafeHtml;
import com.google.gwt.safehtml.shared.SafeHtmlBuilder;
import com.google.gwt.safehtml.shared.SafeHtmlUtils;
import com.google.gwt.text.client.DateTimeFormatRenderer;
import com.google.gwt.text.shared.AbstractRenderer;
import com.google.gwt.text.shared.AbstractSafeHtmlRenderer;
import com.google.gwt.text.shared.Renderer;
import com.google.gwt.text.shared.SafeHtmlRenderer;
import com.puglieseweb.client.managed.request.FeedbackProxy;
import com.puglieseweb.client.scaffold.ScaffoldMobileApp;
import com.puglieseweb.client.scaffold.ui.MobileProxyListView;
import java.util.HashSet;
import java.util.Set;

public abstract class FeedbackMobileListView_Roo_Gwt extends MobileProxyListView<FeedbackProxy> {

    protected Set<String> paths = new HashSet<String>();

    public FeedbackMobileListView_Roo_Gwt(String buttonText, SafeHtmlRenderer<com.puglieseweb.client.managed.request.FeedbackProxy> renderer) {
        super(buttonText, renderer);
    }

    public void init() {
        paths.add("feedback");
        paths.add("name");
    }
}
