// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package com.puglieseweb.client.managed.ui;

import com.google.gwt.core.client.GWT;
import com.google.gwt.dom.client.SpanElement;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.event.dom.client.HasClickHandlers;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.uibinder.client.UiHandler;
import com.google.gwt.user.client.Window;
import com.google.gwt.user.client.ui.Composite;
import com.google.gwt.user.client.ui.HTMLPanel;
import com.google.gwt.user.client.ui.Widget;
import com.puglieseweb.client.managed.request.FeedbackProxy;
import com.puglieseweb.client.scaffold.place.ProxyDetailsView;
import com.puglieseweb.client.scaffold.place.ProxyListView;

public abstract class FeedbackDetailsView_Roo_Gwt extends Composite implements ProxyDetailsView<FeedbackProxy> {

    @UiField
    SpanElement id;

    @UiField
    SpanElement version;

    @UiField
    SpanElement feedback;

    @UiField
    SpanElement name;

    @UiField
    SpanElement email;

    FeedbackProxy proxy;

    @UiField
    SpanElement displayRenderer;

    public void setValue(FeedbackProxy proxy) {
        this.proxy = proxy;
        id.setInnerText(proxy.getId() == null ? "" : String.valueOf(proxy.getId()));
        version.setInnerText(proxy.getVersion() == null ? "" : String.valueOf(proxy.getVersion()));
        feedback.setInnerText(proxy.getFeedback() == null ? "" : String.valueOf(proxy.getFeedback()));
        name.setInnerText(proxy.getName() == null ? "" : String.valueOf(proxy.getName()));
        email.setInnerText(proxy.getEmail() == null ? "" : String.valueOf(proxy.getEmail()));
        displayRenderer.setInnerText(com.puglieseweb.client.managed.ui.FeedbackProxyRenderer.instance().render(proxy));
    }
}
