// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package com.puglieseweb.client.managed.activity;

import com.google.gwt.activity.shared.Activity;
import com.google.gwt.activity.shared.ActivityMapper;
import com.google.gwt.place.shared.Place;
import com.google.gwt.place.shared.PlaceController;
import com.google.inject.Inject;
import com.puglieseweb.client.managed.request.ApplicationEntityTypesProcessor;
import com.puglieseweb.client.managed.request.ApplicationRequestFactory;
import com.puglieseweb.client.managed.request.FeedbackProxy;
import com.puglieseweb.client.managed.ui.FeedbackListView;
import com.puglieseweb.client.managed.ui.FeedbackMobileListView;
import com.puglieseweb.client.scaffold.ScaffoldApp;
import com.puglieseweb.client.scaffold.place.ProxyListPlace;

public abstract class ApplicationMasterActivities_Roo_Gwt implements ActivityMapper {

    protected ApplicationRequestFactory requests;

    protected PlaceController placeController;

    public Activity getActivity(Place place) {
        if (!(place instanceof ProxyListPlace)) {
            return null;
        }
        ProxyListPlace listPlace = (ProxyListPlace) place;
        return new ApplicationEntityTypesProcessor<Activity>() {

            @Override
            public void handleFeedback(FeedbackProxy isNull) {
                setResult(new FeedbackListActivity(requests, ScaffoldApp.isMobile() ? FeedbackMobileListView.instance() : FeedbackListView.instance(), placeController));
            }
        }.process(listPlace.getProxyClass());
    }
}
