<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
  <meta content="text/html; charset=ISO-8859-1"
 http-equiv="Content-Type">
  <title>glossary.html</title>
  <meta content="Emanuele Pugliese" name="author">
</head>
<body>
<h2>Glossary </h2>
<h3><a name="persistent_unit">persistent
units</a></h3>
Sets of
object mappings tied to a particular persistence mapping
implementation such as Hibernate.
</body>
</html>
