// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package com.puglieseweb.client.managed.request;

import com.puglieseweb.shared.gae.MakesGaeRequests;
import com.puglieseweb.shared.scaffold.ScaffoldRequestFactory;

public interface ApplicationRequestFactory extends ScaffoldRequestFactory, MakesGaeRequests {

    FeedbackRequest feedbackRequest();
}
