// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package com.puglieseweb.client.managed.request;

import com.google.gwt.requestfactory.shared.InstanceRequest;
import com.google.gwt.requestfactory.shared.Request;
import com.google.gwt.requestfactory.shared.RequestContext;
import com.google.gwt.requestfactory.shared.ServiceName;
import org.springframework.roo.addon.gwt.RooGwtMirroredFrom;

@RooGwtMirroredFrom("com.puglieseweb.server.domain.Feedback")
@ServiceName("com.puglieseweb.server.domain.Feedback")
public interface FeedbackRequest extends RequestContext {

    abstract Request<java.lang.Long> countFeedbacks();

    abstract Request<java.util.List<com.puglieseweb.client.managed.request.FeedbackProxy>> findAllFeedbacks();

    abstract Request<java.util.List<com.puglieseweb.client.managed.request.FeedbackProxy>> findFeedbackEntries(int firstResult, int maxResults);

    abstract Request<com.puglieseweb.client.managed.request.FeedbackProxy> findFeedback(Long id);

    abstract InstanceRequest<com.puglieseweb.client.managed.request.FeedbackProxy, java.lang.Void> remove();

    abstract InstanceRequest<com.puglieseweb.client.managed.request.FeedbackProxy, java.lang.Void> persist();
}
