// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package com.puglieseweb.client.managed.request;

import com.google.gwt.requestfactory.shared.EntityProxy;
import com.google.gwt.requestfactory.shared.ProxyForName;
import org.springframework.roo.addon.gwt.RooGwtMirroredFrom;

@RooGwtMirroredFrom("com.puglieseweb.server.domain.Feedback")
@ProxyForName("com.puglieseweb.server.domain.Feedback")
public interface FeedbackProxy extends EntityProxy {

    abstract Long getId();

    abstract Integer getVersion();

    abstract String getFeedback();

    abstract String getName();

    abstract String getEmail();

    abstract void setId(Long id);

    abstract void setVersion(Integer version);

    abstract void setFeedback(String feedback);

    abstract void setName(String name);

    abstract void setEmail(String email);
}
